version: '3.7'
services:
  backend:
    build: .
    environment:
      port: 3000
    ports:
      - "5000:3000"

  banco:
    image: "mysql"
    environment: 
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
